// Evento de dos días con los mismos estudiantes: sin reparto del total, cupo completo cada día, el estudiante no elige días.
// Uso: node tests/e2e/mismos-dias.mjs  (app en local con estudiantes cargados)
import { chromium } from '@playwright/test';
import { execFileSync } from 'node:child_process';
const base = process.env.BASE_URL || 'http://localhost:3000';
const nombre = 'Seminario mismos ' + Date.now();
const salida = execFileSync('node', ['tests/e2e/crear-pedido.mjs', '2026-12-16', '09:00', '13:00', nombre, 'interno', '2026-12-17'], { encoding: 'utf8' });
const codigo = (salida.match(/CREADO (SOL-\d{4}-\d{3})/) || [])[1];
if (!codigo || !/MISMOS ESTUDIANTES: 3 y 3/.test(salida) || /INESPERADO|NO DEBERÍA/.test(salida)) throw new Error('no se creó bien el pedido: ' + salida);
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const ctx = await b.newContext({ viewport: { width: 1280, height: 900 } });
const p = await ctx.newPage();
const errores = [];
p.on('pageerror', (e) => errores.push('PAGEERROR ' + e.message));
p.on('dialog', (d) => d.accept(codigo));
const paso = (t) => console.log('·', t);
await p.goto(base + '/coordinacion');
await p.fill('#password', 'protocolo2026');
await p.click('button:has-text("Ingresar")');
await p.waitForSelector('h1:has-text("Coordinación")');
await p.click(`table tbody tr:has-text("${codigo}")`);
await p.waitForSelector('aside');
const panel = (await p.locator('aside').textContent()).replace(/\s+/g, ' ');
if (!/Los mismos 3 estudiantes van los 2 días \(por día: día 1: 0\/3 · día 2: 0\/3\)/.test(panel)) throw new Error('el panel no indica los mismos estudiantes: ' + panel.slice(0, 500));
if (!/D1 · Recepción y registro de invitados · 3/.test(panel) || !/D2 · Apoyo en mesa de honor · 3/.test(panel)) throw new Error('actividades por día: ' + panel.slice(0, 500));
paso('panel: los mismos 3 estudiantes los 2 días, actividades distintas por día');
await p.click('button:has-text("Aprobar y convocar estudiantes")');
await p.waitForSelector('text=Convocatoria abierta', { timeout: 20000 });
const est = await ctx.newPage();
await est.goto(base + '/estudiante?clave=' + codigo);
await est.fill('#correo', 'andres.molina@ute.edu.ec');
await est.click('button:has-text("Ingresar")');
await est.waitForSelector(`text=${nombre}`, { timeout: 15000 });
const card = est.locator(`.blueprint:has-text("${nombre}")`).first();
if ((await card.locator('text=Puedo asistir').count()) !== 0) throw new Error('con los mismos estudiantes no debe pedir elegir días');
await card.locator('button:has-text("Inscribirme")').click();
await est.waitForSelector('text=por confirmar', { timeout: 15000 });
paso('estudiante inscrito a los dos días sin elegir');
await p.reload();
await p.click(`table tbody tr:has-text("${codigo}")`);
await p.locator('aside .linea-item:has-text("Andrés") button:has-text("Aceptar")').click();
await p.waitForSelector('text=/por día: día 1: 1\\/3 · día 2: 1\\/3/', { timeout: 15000 });
paso('confirmado en los dos días: 1/3 · 1/3');
await p.click('aside button:has-text("Eliminar pedido")');
await p.waitForSelector(`table tbody tr:has-text("${codigo}")`, { state: 'detached', timeout: 15000 });
paso('pedido de prueba eliminado');
console.log(errores.length ? errores.join('\n') : 'sin errores de consola');
await b.close();
