// Reparto por actividad en el paso 3: con la suma descuadrada no se puede continuar; cuadrada, sí. Uso: node tests/e2e/reparto.mjs
import { chromium } from '@playwright/test';
import { writeFileSync } from 'node:fs';
const base = process.env.BASE_URL || 'http://localhost:3000';
const shots = process.env.SHOTS || '/tmp/claude-0/-home-user-PFCGYT/5a10c32a-d366-574f-b48c-ac6051283a90/scratchpad/shots';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const p = await b.newPage({ viewport: { width: 1280, height: 900 } });
p.on('pageerror', (e) => console.log('PAGEERROR', e.message));
const paso = (t) => console.log('·', t);
const asignados = () => p.locator('p:has-text("Asignados:")').first().textContent();
const bloqueado = () => p.locator('button:has-text("Continuar")').isDisabled();
await p.goto(base + '/');
const tmp = '/tmp/evidencia-prueba.pdf'; writeFileSync(tmp, '%PDF-1.4\n1 0 obj<<>>endobj\ntrailer<<>>\n%%EOF');
await p.fill('#nombre', 'Carla Espinosa'); await p.fill('#cargo', 'Directora'); await p.fill('#institucion', 'Universidad UTE'); await p.fill('#correo', 'carla@ejemplo.com');
await p.click('button:has-text("Continuar")');
await p.fill('#evento', 'Cena de gala'); await p.setInputFiles('input[type=file]', tmp); await p.waitForSelector('.tag-accent', { timeout: 15000 });
await p.fill('#dia-fecha-0', '2026-10-20'); await p.fill('#dia-inicio-0', '17:00'); await p.fill('#dia-fin-0', '21:00');
await p.fill('#lugar', 'Auditorio'); await p.fill('#responsable', 'Secretaría'); await p.fill('#telefono', '0991234567');
await p.waitForTimeout(600);
if (await bloqueado()) throw new Error('paso 2 bloqueado: ' + (await p.locator('.alerta').allTextContents()).join(' | '));
await p.click('button:has-text("Continuar")');
await p.waitForSelector('#cantidad');
await p.fill('#cantidad', '4');
if (!(await bloqueado())) throw new Error('sin actividades marcadas se pudo continuar');
paso('sin actividades: bloqueado');
await p.click('label:has-text("Guía de invitados")');
await p.click('label:has-text("Acompañamiento en recorridos")');
let t = await asignados();
if (!/Asignados: 4 de 4/.test(t) || (await bloqueado())) throw new Error('al marcar dos actividades no cuadró solo: ' + t);
paso('dos actividades: ' + t.trim());
const guia = p.locator('input[aria-label="Estudiantes en Guía de invitados"]');
const recorridos = p.locator('input[aria-label="Estudiantes en Acompañamiento en recorridos"]');
await guia.fill('2'); await p.waitForTimeout(300);
t = await asignados();
if (!/Asignados: 3 de 4/.test(t) || !/faltan 1/.test(t) || !(await bloqueado())) throw new Error('descuadre no bloquea: ' + t);
paso('descuadrado (2 + 1): ' + t.trim() + ' · bloqueado');
await p.screenshot({ path: shots + '/paso3-descuadre.png', fullPage: true, caret: 'initial' });
await recorridos.fill('2'); await p.waitForTimeout(300);
t = await asignados();
if (!/Asignados: 4 de 4/.test(t) || (await bloqueado())) throw new Error('cuadrado pero sigue bloqueado: ' + t);
paso('cuadrado (2 + 2): ' + t.trim() + ' · se puede continuar');
await p.screenshot({ path: shots + '/paso3-reparto.png', fullPage: true, caret: 'initial' });
await p.click('button:has-text("Continuar")');
await p.waitForSelector('text=Guía de invitados (2), Acompañamiento en recorridos (2)');
paso('resumen del paso 4 muestra el reparto');
await b.close();
